import { Parameters } from ".";

export default {
  title: "Components/Parameters",
  component: Parameters,
};

export const Default = {
  args: {
    className: {},
    textClassName: {},
    xPosKpClassName: {},
    groupClassName: {},
    overlapGroupClassName: {},
    xPosKpClassNameOverride: {},
    textClassNameOverride: {},
    yPosKpClassName: {},
    groupClassNameOverride: {},
    overlapGroupClassNameOverride: {},
    yPosKpClassNameOverride: {},
    divClassName: {},
    xPosKiClassName: {},
    overlapGroupWrapperClassName: {},
    xPosKiWrapperClassName: {},
    xPosKiClassNameOverride: {},
    divClassNameOverride: {},
    yPosKiClassName: {},
    overlapGroupWrapperClassNameOverride: {},
    yPosKiWrapperClassName: {},
    yPosKiClassNameOverride: {},
    textClassName1: {},
    xPosKdClassName: {},
    groupClassName1: {},
    xPosKdWrapperClassName: {},
    xPosKdClassNameOverride: {},
    textClassName2: {},
    yPosKdClassName: {},
    groupClassName2: {},
    yPosKdWrapperClassName: {},
    yPosKdClassNameOverride: {},
    textClassName3: {},
    xVelKpClassName: {},
    groupClassName3: {},
    xVelKpWrapperClassName: {},
    xVelKpClassNameOverride: {},
    textClassName4: {},
    yVelKpClassName: {},
    groupClassName4: {},
    yVelKpWrapperClassName: {},
    yVelKpClassNameOverride: {},
    textClassName5: {},
    xVelKiClassName: {},
    groupClassName5: {},
    xVelKiWrapperClassName: {},
    xVelKiClassNameOverride: {},
    textClassName6: {},
    yVelKiClassName: {},
    groupClassName6: {},
    yVelKiWrapperClassName: {},
    yVelKiClassNameOverride: {},
    textClassName7: {},
    xVelKdClassName: {},
    groupClassName7: {},
    xVelKdWrapperClassName: {},
    xVelKdClassNameOverride: {},
    textClassName8: {},
    yVelKdClassName: {},
    groupClassName8: {},
    yVelKdWrapperClassName: {},
    yVelKdClassNameOverride: {},
    textClassName9: {},
    xSetPointClassName: {},
    groupClassName9: {},
    xSetPointWrapperClassName: {},
    xSetPointClassNameOverride: {},
    textClassName10: {},
    ySetPointClassName: {},
    groupClassName10: {},
    ySetPointWrapperClassName: {},
    ySetPointClassNameOverride: {},
    pleaseEnterYourClassName: {},
  },
};
